// Classify the request client from its User-Agent into a small, stable set of
// buckets, and fold that plus an explicit ?test=1 override into a test/prod
// source label. Used to separate real TRMNL polls from our own test traffic in
// telemetry. The buckets are intentionally coarse; index.js logs the raw UA
// alongside (Workers Logs) for when the exact string matters.

// Coarse UA → client bucket. Order matters: Faraday is checked before Ruby so a
// Faraday UA never falls through to the trmnlp bucket.
//   trmnl   — TRMNL's backend poller (Rails/Faraday)
//   trmnlp  — local preview tool (Ruby HTTP client)
//   curl    — our curl tests
//   browser — a browser hitting the worker directly (e.g. xhrSelectSearch)
//   other   — bots, unknown clients, or a missing UA
export function classifyClient(userAgent) {
    const ua = (userAgent || "").toLowerCase();
    if (ua.includes("faraday")) return "trmnl";
    if (ua.includes("ruby")) return "trmnlp";
    if (ua.includes("curl")) return "curl";
    if (ua.includes("mozilla")) return "browser";
    return "other";
}

// Our own dev tools. Their traffic is always test, no ?test=1 needed.
const TEST_CLIENTS = new Set(["trmnlp", "curl"]);

// test  — explicitly marked (?test=1) or generated by one of our dev tools.
// prod  — everything else, including unknown clients. Defaulting unknowns to
//         prod means a TRMNL UA change degrades to over-counting prod rather
//         than silently dropping real traffic; use client === "trmnl" for the
//         tight "confirmed real installs" view.
export function classifySource(client, testFlag) {
    if (testFlag) return "test";
    return TEST_CLIENTS.has(client) ? "test" : "prod";
}
